version: '3.9'

services:
  app:
    image: "python:3.7"
    entrypoint: "python -m http.server 9000"
    ports:
      - 9000:9000
    depends_on:
      - db
    profiles:
      - dev
      - prod

  db:
    image: "mongo:4.0.17-xenial"

  mongo_express:
    image: "mongo-express:0.49"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    ports: 
      - 8081:8081
    profiles:
      - dev
