version: '3'

services:
  app:
    image: "python:3.7"
    depends_on:
      - mongo
    networks:
      - my_net1

  mongo:
    image: "mongo:4.0.17-xenial"

networks:
# Global networks
  my_net1:


