version: '3'

services:
  app:
    image: "python:3.7"
    depends_on:
      - mongo

  mongo:
    image: "mongo:4.0.17-xenial"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"] # Команда для проверки работоспособности
      interval: 10s    # Интервал для периодического запуска
      timeout: 1s       # Таймаут ожидания завершения команды
      retries: 2         # Максимлаьное количество неудачных попыток запуска команды
      start_period: 4s  # Через сколько секунд после запуска контейнера начинать проверки (время на инициализацию)
  

