version: '3'

services:
  app:
    image: "python:3.7"
    depends_on:
      - mongo

  mongo:
    image: "mongo:4.0.17-xenial"

networks:
# Using existing external network
  default:
    external:
      name: existing_network 
  

