version: '3'

services:
  app1:
    image: "mongo:4.0.17-xenial"
    volumes:
      - my_vol:/data1

  app2:
    image: "mongo:4.0.17-xenial"
    volumes:
      - my_vol:/data2

# Будет использован внешний vol
volumes:
  my_vol:
    external: true
