version: '3'

services:
  app:
    image: "python:3.7"
    depends_on:
      - mongo

  mongo:
    image: "mongo:4.0.17-xenial"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"] # Команда для проверки работоспособности
      interval: 1m30s    # Интервал для периодического запуска
      timeout: 10s       # Таймаут ожидания завершения команды
      retries: 3         # Максимлаьное количество неудачных попыток запуска команды
      start_period: 40s  # Через сколько секунд после запуска контейнера начинать проверки (время на инициализацию)
  

